title: "M A Rahman"
logo: "/images/Profile img.png"
description: >
  Aspiring data scientist skilled in statistical analysis, machine learning, and data visualization. Proficient in Python and SQL. Experienced in developing
  predictive models, conducting EDA, and deploying machine learning solutions. Strong problem-solving
  abilities with a passion for continuous learning and
  professional growth.
show_downloads: true
theme: jekyll-theme-minimal

